package engine

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"

	"gavel/internal/exercise"
)

// resultPrefix marks the harness output lines that carry test results.
const resultPrefix = "@@RESULT@@ "

// nonceEnv is the environment variable that passes the per-run nonce to the
// harness. Every result line must carry it, so that the student cannot
// forge results by printing lines with the prefix.
const nonceEnv = "GAVEL_NONCE"

// errTimeout is the error reported for a test that exceeded its time limit.
const errTimeout = "timeout"

// harnessTemplate generates the main package that drives the student's
// function. Types come from a validated exercise, so they are safe to
// splice into source code.
var harnessTemplate = template.Must(template.New("harness").Parse(`// Code generated by gavel. DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"time"

	"sandbox/solution"
)

const timeout = {{.TimeoutMS}} * time.Millisecond

type result struct {
	Nonce      string          ` + "`json:\"nonce\"`" + `
	Index      int             ` + "`json:\"index\"`" + `
	Got        json.RawMessage ` + "`json:\"got,omitempty\"`" + `
	Error      string          ` + "`json:\"error,omitempty\"`" + `
	DurationMS int64           ` + "`json:\"duration_ms\"`" + `
}

type outcome struct {
	got json.RawMessage
	err string
}

func main() {
	var tests [][]json.RawMessage
	if err := json.NewDecoder(os.Stdin).Decode(&tests); err != nil {
		fmt.Fprintln(os.Stderr, "harness: invalid input:", err)
		os.Exit(2)
	}
	// Anything the student prints from now on goes to stderr. Output
	// printed earlier (from package initialisers) cannot carry the nonce,
	// which the student has no way to read.
	nonce := os.Getenv("{{.NonceEnv}}")
	out := os.Stdout
	os.Stdout = os.Stderr
	for i, input := range tests {
		res := run(i, input)
		res.Nonce = nonce
		data, err := json.Marshal(res)
		if err != nil {
			fmt.Fprintln(os.Stderr, "harness:", err)
			os.Exit(2)
		}
		fmt.Fprintf(out, "\n{{.Prefix}}%s\n", data)
		if res.Error == "{{.Timeout}}" {
			// The stuck goroutine dies with the process.
			os.Exit(0)
		}
	}
}

func run(index int, input []json.RawMessage) result {
	res := result{Index: index}
	if len(input) != {{len .Params}} {
		res.Error = fmt.Sprintf("esperados {{len .Params}} argumentos, recebidos %d", len(input))
		return res
	}
{{- range $i, $p := .Params}}
	var a{{$i}} {{$p}}
	if err := json.Unmarshal(input[{{$i}}], &a{{$i}}); err != nil {
		res.Error = fmt.Sprintf("argumento {{$i}} inválido: %v", err)
		return res
	}
{{- end}}
	done := make(chan outcome, 1)
	start := time.Now()
	go func() {
		defer func() {
			if r := recover(); r != nil {
				done <- outcome{err: fmt.Sprintf("panic: %v", r)}
			}
		}()
		got := solution.{{.Function}}({{range $i, $p := .Params}}{{if $i}}, {{end}}a{{$i}}{{end}})
		data, err := json.Marshal(got)
		if err != nil {
			done <- outcome{err: "resultado não serializável: " + err.Error()}
			return
		}
		done <- outcome{got: data}
	}()
	timer := time.NewTimer(timeout)
	defer timer.Stop()
	select {
	case o := <-done:
		res.Got, res.Error = o.got, o.err
	case <-timer.C:
		res.Error = "{{.Timeout}}"
	}
	res.DurationMS = time.Since(start).Milliseconds()
	return res
}
`))

// generateHarness returns the formatted source of the harness main.go.
func generateHarness(ex *exercise.Exercise) ([]byte, error) {
	var buf bytes.Buffer
	data := struct {
		*exercise.Exercise
		Prefix   string
		Timeout  string
		NonceEnv string
	}{ex, resultPrefix, errTimeout, nonceEnv}
	if err := harnessTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executar template do harness: %w", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatar harness: %w", err)
	}
	return src, nil
}
